import Head from 'next/head'

import styles from '../styles/Temp.module.css'

export default function Temp() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BM Bike</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <img src={"/images/logo.png"} width="300x" height="300px" />


      <h1 style={{color:"#28245c", textAlign:"center"}}>EM BREVE!</h1>
      
      </main>
    </div>
  )
}
